version: '3.8'

services:
  exchange:
    image: exchange-orderbook:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./etc/exchange/conf.toml:/etc/exchange/conf.toml
    networks:
      - exchange-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres://exchange_user:exchange_password@postgres:5432/exchange
      - RUST_LOG="info,exchange=trace,tower_http=debug"
      - CONFIG_FILE_PATH=/etc/exchange/conf.toml
    depends_on:
      - redis
      - postgres
    restart: on-failure # Restart the service if it fails
    stop_signal: SIGINT # Stop the service gracefully

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/letsencrypt/:/etc/letsencrypt:ro
    networks:
      - exchange-net
    depends_on:
      - exchange
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379" # Expose Redis ports for debugging
    networks:
      - exchange-net
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - exchange-net
    environment:
      - POSTGRES_DB=exchange_db
      - POSTGRES_USER=exchange_user
      - POSTGRES_PASSWORD=exchange_password
      - TZ=UTC
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

networks:
  exchange-net:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
